name: Template Update

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  check_template_updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Execute Template Update Action
      uses: dondakeshimo/tmpl-cf@main
      with:
        config-file: 'tmpl_cf.json'
        access-token: ${{ secrets.GITHUB_TOKEN }}
